"""Framework-independent financial domain primitives."""

from hermes_finance.domain.accounts import AccountStatus, AccountType
from hermes_finance.domain.cash_boundary_coverage import (
    CashBoundaryCoverage,
    CashBoundaryCoverageEvidence,
    CashBoundaryCoverageState,
    CashBoundaryCoverageStatus,
)
from hermes_finance.domain.cash_flows import ExpectedCashFlowType, InvestmentCashFlowType
from hermes_finance.domain.debts import DebtType
from hermes_finance.domain.deposits import DepositType
from hermes_finance.domain.expenses import ExpenseType
from hermes_finance.domain.external_flows import (
    BoundaryFlowDirection,
    BoundaryFlowKind,
    ExternalFlowClassification,
    ExternalFlowDirection,
    ExternalFlowKind,
    ExternalFlowScope,
    ExternalFlowScopeMembership,
    ExternalTransferReconciliationKind,
    ExternalTransferStatus,
    TransferLinkStatus,
)
from hermes_finance.domain.goals import GoalType
from hermes_finance.domain.iis import TaxBenefitStatus
from hermes_finance.domain.in_kind_boundary_coverage import (
    InKindBoundaryCoverage,
    InKindBoundaryCoverageEvidence,
    InKindBoundaryCoverageState,
    InKindBoundaryCoverageStatus,
    InKindMovementEvidence,
    InKindMovementKind,
)
from hermes_finance.domain.incomes import IncomeType
from hermes_finance.domain.instruments import InstrumentType, MarketMappingState
from hermes_finance.domain.month_close_workflow import (
    GuidedCloseAction,
    GuidedCloseActionId,
    GuidedCloseActionTarget,
    GuidedCloseApplicability,
    GuidedCloseCompletionBasis,
    GuidedCloseEvidenceScope,
    GuidedCloseGate,
    GuidedCloseReasonCode,
    GuidedCloseStale,
    GuidedCloseStep,
    GuidedCloseStepId,
    GuidedCloseStepState,
    derive_step_state,
    recommended_step_id,
)
from hermes_finance.domain.performance_attribution import (
    ExternalFlowSummary,
    Perf04aBridgePrerequisites,
    Perf04aCoverageEvidence,
    Perf04aEvidence,
    Perf04aValuationEvidence,
    PerformanceAttributionQuality,
    PerformanceAttributionResult,
)
from hermes_finance.domain.performance_availability import (
    AvailabilityReasonCode,
    ExternalFlowCoverage,
    ExternalFlowEvidence,
    PerformanceAvailability,
    PerformanceAvailabilityReasonCode,
    PerformanceAvailabilityStatus,
    PerformanceMetricPrerequisites,
    ScopeMembershipCoverage,
    ValuationBoundaryEvidence,
)
from hermes_finance.domain.positions import PriceSource
from hermes_finance.domain.reporting import ReportingMonthSource, ReportingMonthStatus
from hermes_finance.domain.twrr import (
    TwrrAvailabilityStatus,
    TwrrBoundary,
    TwrrQuality,
    TwrrReasonCode,
    TwrrResult,
    calculate_twrr,
)
from hermes_finance.domain.valuation_boundaries import (
    ExternalFlowBoundaryEvidence,
    ObservedValuationEvidence,
    ObservedValuationPoint,
    ValuationBoundaryRelation,
)
from hermes_finance.domain.valuation_points import (
    ComponentStatus,
    CoverageStatus,
    PerformanceScope,
    ValuationComponent,
    ValuationPoint,
    ValuationPointStatus,
    ValuationProvenance,
    ValuationQuality,
    ValuationReasonCode,
    build_valuation_point,
)
from hermes_finance.domain.values import (
    FINANCIAL_ROUNDING,
    PercentageRate,
    RubleAmount,
)
from hermes_finance.domain.xirr import (
    XirrAvailabilityStatus,
    XirrCashFlow,
    XirrQuality,
    XirrReasonCode,
    XirrResult,
    calculate_xirr,
)

__all__ = [
    "FINANCIAL_ROUNDING",
    "CashBoundaryCoverage",
    "CashBoundaryCoverageEvidence",
    "CashBoundaryCoverageState",
    "CashBoundaryCoverageStatus",
    "AccountStatus",
    "AccountType",
    "DebtType",
    "BoundaryFlowDirection",
    "BoundaryFlowKind",
    "ExpectedCashFlowType",
    "ExternalFlowClassification",
    "ExternalFlowDirection",
    "ExternalFlowKind",
    "ExternalFlowScope",
    "ExternalFlowScopeMembership",
    "ExternalTransferReconciliationKind",
    "ExternalTransferStatus",
    "DepositType",
    "ExpenseType",
    "GoalType",
    "InvestmentCashFlowType",
    "IncomeType",
    "InKindBoundaryCoverage",
    "InKindBoundaryCoverageEvidence",
    "InKindBoundaryCoverageState",
    "InKindBoundaryCoverageStatus",
    "InKindMovementEvidence",
    "InKindMovementKind",
    "InstrumentType",
    "MarketMappingState",
    "GuidedCloseAction",
    "GuidedCloseActionId",
    "GuidedCloseActionTarget",
    "GuidedCloseApplicability",
    "GuidedCloseCompletionBasis",
    "GuidedCloseEvidenceScope",
    "GuidedCloseGate",
    "GuidedCloseReasonCode",
    "GuidedCloseStale",
    "GuidedCloseStep",
    "GuidedCloseStepId",
    "GuidedCloseStepState",
    "derive_step_state",
    "recommended_step_id",
    "AvailabilityReasonCode",
    "ExternalFlowCoverage",
    "ExternalFlowEvidence",
    "PerformanceAvailability",
    "PerformanceAvailabilityReasonCode",
    "PerformanceAvailabilityStatus",
    "PerformanceMetricPrerequisites",
    "ScopeMembershipCoverage",
    "ValuationBoundaryEvidence",
    "ExternalFlowSummary",
    "Perf04aBridgePrerequisites",
    "Perf04aCoverageEvidence",
    "Perf04aEvidence",
    "Perf04aValuationEvidence",
    "PerformanceAttributionQuality",
    "PerformanceAttributionResult",
    "ExternalFlowBoundaryEvidence",
    "ObservedValuationEvidence",
    "ObservedValuationPoint",
    "ValuationBoundaryRelation",
    "PercentageRate",
    "PriceSource",
    "ReportingMonthSource",
    "ReportingMonthStatus",
    "RubleAmount",
    "XirrAvailabilityStatus",
    "XirrCashFlow",
    "XirrQuality",
    "XirrReasonCode",
    "XirrResult",
    "calculate_xirr",
    "TwrrAvailabilityStatus",
    "TwrrBoundary",
    "TwrrQuality",
    "TwrrReasonCode",
    "TwrrResult",
    "calculate_twrr",
    "ComponentStatus",
    "CoverageStatus",
    "PerformanceScope",
    "ValuationComponent",
    "ValuationPoint",
    "ValuationPointStatus",
    "ValuationProvenance",
    "ValuationQuality",
    "ValuationReasonCode",
    "build_valuation_point",
    "TaxBenefitStatus",
    "TransferLinkStatus",
]
